from .auth import router as auth_router
from .questions import router as questions_router
from .dashboard import router as dashboard_router
from .gamification import router as gamification_router
from .writing import router as writing_router
from .speaking import router as speaking_router
from .vocabulary import router as vocabulary_router
from .generator import router as generator_router
from .mock_router import router as mock_router
