"""Service for evaluating IELTS speaking audio using Google Gemini Multimodal."""

import os
import json
import google.generativeai as genai
from typing import Dict, Any
from dotenv import load_dotenv

from ..config import get_settings
from .ai_provider import complete_json_with_ollama, extract_json, provider_order, with_provider_meta

load_dotenv()

# Configure Gemini
api_key = os.getenv("GEMINI_API_KEY")
if api_key:
    genai.configure(api_key=api_key)


def analyze_audio_locally(audio_path: str, prompt_text: str) -> Dict[str, Any]:
    """Deterministic local fallback for speaking when Gemini is not configured."""
    file_size = os.path.getsize(audio_path) if os.path.exists(audio_path) else 0
    estimated_seconds = max(10, min(180, file_size // 1800))
    band = 6.0 if estimated_seconds >= 60 else 5.0 if estimated_seconds >= 30 else 4.0
    return {
        "error": "Gemini API key not configured",
        "band_score": band,
        "transcription": "",
        "fluency_coherence": {
            "score": band,
            "comment": f"Local fallback: recording length is estimated at about {estimated_seconds} seconds.",
        },
        "lexical_resource": {
            "score": band,
            "comment": "Local fallback: vocabulary cannot be transcribed without AI. Practice topic-specific phrases.",
        },
        "grammatical_range": {
            "score": band,
            "comment": "Local fallback: grammar cannot be checked without transcription. Use complete sentences and varied clauses.",
        },
        "pronunciation": {
            "score": band,
            "comment": "Local fallback: pronunciation cannot be scored precisely without AI audio analysis.",
        },
        "overall_feedback": "Gemini is not configured, so this is deterministic local speaking feedback. Your attempt is still saved to history.",
        "improvements": [
            "Record for the full IELTS time limit.",
            "Answer directly, extend with examples, and avoid long silent pauses.",
            "Configure GEMINI_API_KEY for transcription and pronunciation feedback.",
        ],
        "annotated_errors": [],
    }


def _transcribe_with_local_whisper(audio_path: str) -> str | None:
    try:
        import whisper  # type: ignore
    except Exception:
        return None
    try:
        model = whisper.load_model(get_settings().whisper_model)
        result = model.transcribe(audio_path, language="en")
        return str(result.get("text", "")).strip()
    except Exception as e:
        print(f"Local Whisper transcription error: {e}")
        return None


def _speaking_prompt(transcript: str, prompt_text: str) -> str:
    return f"""
You are an IELTS Speaking examiner. Evaluate the spoken response transcript.

Prompt:
{prompt_text}

Transcript:
{transcript}

Return strictly valid JSON only:
{{
  "band_score": <float 0-9>,
  "transcription": "{transcript}",
  "fluency_coherence": {{"score": <float>, "comment": "<short actionable comment>"}},
  "lexical_resource": {{"score": <float>, "comment": "<short actionable comment>"}},
  "grammatical_range": {{"score": <float>, "comment": "<short actionable comment>"}},
  "pronunciation": {{"score": <float>, "comment": "Pronunciation cannot be fully judged from transcript-only local analysis."}},
  "overall_feedback": "<2-4 sentence IELTS examiner feedback>",
  "improvements": ["<action 1>", "<action 2>", "<action 3>"],
  "annotated_errors": []
}}
"""


def _valid_speaking_result(result: Dict[str, Any] | None, transcript: str = "") -> Dict[str, Any] | None:
    if not result or "band_score" not in result:
        return None
    result.setdefault("transcription", transcript)
    for key in ["fluency_coherence", "lexical_resource", "grammatical_range", "pronunciation"]:
        if not isinstance(result.get(key), dict):
            result[key] = {"score": float(result.get("band_score", 0.0)), "comment": "No criterion comment returned."}
        result[key].setdefault("score", float(result.get("band_score", 0.0)))
        result[key].setdefault("comment", "No criterion comment returned.")
    result.setdefault("overall_feedback", "Feedback generated by the configured AI provider.")
    result.setdefault("improvements", [])
    result.setdefault("annotated_errors", [])
    return result


def _analyze_audio_with_gemini(audio_path: str, prompt_text: str) -> Dict[str, Any] | None:
    if not api_key:
        return None
    try:
        audio_file = genai.upload_file(path=audio_path)
        model = genai.GenerativeModel('gemini-1.5-flash')
        system_prompt = f"""
You are an expert IELTS Speaking examiner. Listen to the user's response to this prompt: "{prompt_text}".
Evaluate Fluency and Coherence, Lexical Resource, Grammatical Range and Accuracy, and Pronunciation.
Return strictly valid JSON with keys: band_score, transcription, fluency_coherence, lexical_resource, grammatical_range, pronunciation, overall_feedback, improvements, annotated_errors.
"""
        response = model.generate_content([system_prompt, audio_file])
        return extract_json(response.text)
    except Exception as e:
        print(f"Gemini speaking evaluation error: {e}")
        return None


async def analyze_audio_with_gemini(
    audio_path: str,
    prompt_text: str
) -> Dict[str, Any]:
    """
    Evaluates IELTS speaking audio using Gemini 1.5 Flash.
    """
    transcript = _transcribe_with_local_whisper(audio_path)
    for provider in provider_order():
        if provider == "ollama" and transcript:
            result = _valid_speaking_result(complete_json_with_ollama(_speaking_prompt(transcript, prompt_text)), transcript)
            if result:
                return with_provider_meta(result, "ollama+whisper")
        if provider == "gemini":
            result = _valid_speaking_result(_analyze_audio_with_gemini(audio_path, prompt_text))
            if result:
                return with_provider_meta(result, "gemini")
        if provider == "local":
            fallback = analyze_audio_locally(audio_path, prompt_text)
            if transcript:
                fallback["transcription"] = transcript
                fallback["overall_feedback"] = "Local Whisper produced a transcript, but no local LLM was available for full IELTS feedback."
            return with_provider_meta(fallback, "local")
    return with_provider_meta(analyze_audio_locally(audio_path, prompt_text), "local")
