"""Service for evaluating IELTS writing tasks using Google Gemini."""

import os
import json
import google.generativeai as genai
from typing import Dict, Any
from dotenv import load_dotenv

from .ai_provider import complete_json_with_ollama, extract_json, provider_order, with_provider_meta

load_dotenv()

# Configure Gemini
api_key = os.getenv("GEMINI_API_KEY")
if api_key:
    genai.configure(api_key=api_key)


def evaluate_essay_locally(essay_text: str, task_type: str, prompt_text: str) -> Dict[str, Any]:
    """Deterministic local IELTS-style fallback when Gemini is not configured."""
    words = [word for word in essay_text.split() if word.strip()]
    word_count = len(words)
    sentences = [s for s in essay_text.replace("?", ".").replace("!", ".").split(".") if s.strip()]
    unique_ratio = len({w.lower().strip(".,;:!?") for w in words}) / max(word_count, 1)

    target_words = 150 if "1" in task_type else 250
    length_score = 6.5 if word_count >= target_words else 6.0 if word_count >= target_words * 0.75 else 5.0 if word_count >= target_words * 0.5 else 4.0
    coherence_score = 6.5 if len(sentences) >= 8 else 6.0 if len(sentences) >= 5 else 5.0
    lexical_score = 6.5 if unique_ratio >= 0.55 else 6.0 if unique_ratio >= 0.42 else 5.0
    grammar_score = 6.5 if word_count >= target_words and len(sentences) >= 6 else 6.0 if word_count >= target_words * 0.75 else 5.0
    band = round((length_score + coherence_score + lexical_score + grammar_score) * 2 / 4) / 2

    return {
        "band_score": band,
        "task_response": {
            "score": length_score,
            "comment": f"Local fallback: response length is {word_count} words against a target of about {target_words}.",
        },
        "coherence_cohesion": {
            "score": coherence_score,
            "comment": "Local fallback: score estimated from paragraph/sentence development. Add clearer topic sentences and linking.",
        },
        "lexical_resource": {
            "score": lexical_score,
            "comment": "Local fallback: score estimated from vocabulary variety. Add precise academic collocations.",
        },
        "grammatical_range": {
            "score": grammar_score,
            "comment": "Local fallback: score estimated from sentence coverage. Mix simple and complex structures carefully.",
        },
        "overall_feedback": "Gemini is not configured, so this is deterministic local IELTS-style feedback. It is useful for practice tracking, but not a substitute for examiner feedback.",
        "improvements": [
            "State a clear position and develop it with specific examples.",
            "Use cohesive devices naturally instead of repeating the same connector.",
            "Review grammar accuracy after writing, especially articles and verb forms.",
        ],
        "annotated_errors": [],
        "error": "Using deterministic local fallback",
    }

def _writing_prompt(essay_text: str, task_type: str, prompt_text: str) -> str:
    return f"""
You are an IELTS Writing examiner. Evaluate this {task_type} response.

Prompt:
{prompt_text}

Essay:
{essay_text}

Return strictly valid JSON only:
{{
  "band_score": <float 0-9>,
  "task_response": {{"score": <float>, "comment": "<short actionable comment>"}},
  "coherence_cohesion": {{"score": <float>, "comment": "<short actionable comment>"}},
  "lexical_resource": {{"score": <float>, "comment": "<short actionable comment>"}},
  "grammatical_range": {{"score": <float>, "comment": "<short actionable comment>"}},
  "overall_feedback": "<2-4 sentence IELTS examiner feedback>",
  "improvements": ["<action 1>", "<action 2>", "<action 3>"],
  "annotated_errors": []
}}
"""


def _valid_writing_result(result: Dict[str, Any] | None) -> Dict[str, Any] | None:
    if not result or "band_score" not in result:
        return None
    for key in ["task_response", "coherence_cohesion", "lexical_resource", "grammatical_range"]:
        if not isinstance(result.get(key), dict):
            result[key] = {"score": float(result.get("band_score", 0.0)), "comment": "No criterion comment returned."}
        result[key].setdefault("score", float(result.get("band_score", 0.0)))
        result[key].setdefault("comment", "No criterion comment returned.")
    result.setdefault("overall_feedback", "Feedback generated by the configured AI provider.")
    result.setdefault("improvements", [])
    result.setdefault("annotated_errors", [])
    return result


def _evaluate_essay_with_gemini(essay_text: str, task_type: str, prompt_text: str) -> Dict[str, Any] | None:
    if not api_key:
        return None
    try:
        model = genai.GenerativeModel('gemini-1.5-flash')
        response = model.generate_content(_writing_prompt(essay_text, task_type, prompt_text))
        return extract_json(response.text)
    except Exception as e:
        print(f"Gemini evaluation error: {e}")
        return None


async def evaluate_essay_with_gemini(
    essay_text: str,
    task_type: str,  # "Task 1" or "Task 2"
    prompt_text: str
) -> Dict[str, Any]:
    """
    Evaluates an IELTS essay using Gemini 1.5 Flash.
    Returns structured feedback and band score.
    """
    prompt = _writing_prompt(essay_text, task_type, prompt_text)
    for provider in provider_order():
        if provider == "ollama":
            result = _valid_writing_result(complete_json_with_ollama(prompt))
            if result:
                return with_provider_meta(result, "ollama")
        if provider == "gemini":
            result = _valid_writing_result(_evaluate_essay_with_gemini(essay_text, task_type, prompt_text))
            if result:
                return with_provider_meta(result, "gemini")
        if provider == "local":
            return with_provider_meta(evaluate_essay_locally(essay_text, task_type, prompt_text), "local")
    return with_provider_meta(evaluate_essay_locally(essay_text, task_type, prompt_text), "local")
